cam0:
  camera_model: pinhole
  intrinsics: [840.28, 838.01, 746.80, 550.76]
  distortion_model: equidistant
  distortion_coeffs: [-0.0121, -0.0075, 0.0017, -0.0007]
  resolution: [1440, 1080]
  image_topic: /camera/image
  rostopic: /camera/image
  # image_transport: raw
  tag_topic: /cam_sync/cam_0/detector/tags
  tagtopic: /camera/tags
  tag_detector: umich
  rig_body: rig
