cam0:
  camera_model: pinhole
  intrinsics: [1404.917, 1403.505, 962.317, 605.784]
  distortion_model: radtan
  distortion_coeffs: [-0.161604, 0.093674, -0.000037, -0.000336, 0.000000]
  resolution: [1920, 1200]
  image_topic: /cam_sync/cam_0/image_raw
  # image_transport: ffmpeg
  tag_topic: /cam_sync/cam_0/detector/tags
  tag_detector: umich
  rig_body: rig
cam1:
  camera_model: pinhole
  intrinsics: [1404.917, 1403.505, 962.317, 605.784]
  distortion_model: radtan
  distortion_coeffs: [-0.161604, 0.093674, -0.000037, -0.000336, 0.000000]
  resolution: [1920, 1200]
  image_topic: /cam_sync/cam_1/image_raw
  # image_transport: ffmpeg
  tag_topic: /cam_sync/cam_1/detector/tags
  tag_detector: umich
  rig_body: rig
