#
# continuous integration workflow
#
name: build repo

on:
  push:
    branches: [ros2]
  pull_request:
    branches: [ros2]
  workflow_dispatch:
    branches: [ros2]

jobs:
  build_ros2:
    uses: ros-misc-utilities/ros_build_scripts/.github/workflows/ros2_recent_ci.yml@master
    with:
      repo: ${{ github.event.repository.name }}
      vcs_url: https://raw.githubusercontent.com/${{ github.repository }}/ros2/${{ github.event.repository.name }}.repos
